# Generated by Django 6.0 on 2026-02-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
