# Generated by Django 6.0 on 2025-12-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0003_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField()),
                ('tasks_in_progress', models.IntegerField()),
                ('tasks_awaiting_feedback', models.IntegerField()),
                ('urgent_tasks', models.IntegerField()),
                ('tasks_to_do', models.IntegerField()),
                ('tasks_done', models.IntegerField()),
            ],
        ),
    ]
