# Generated by Django 6.0 on 2025-12-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0006_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
