# Generated by Django 6.0 on 2025-12-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0007_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='process',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('awaiting_feedback', 'Awaiting Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
    ]
