# Generated by Django 6.0 on 2025-12-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0009_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='join_app.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ManyToManyField(related_name='tasks', to='join_app.contact'),
        ),
    ]
