# Generated by Django 6.0 on 2025-12-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0012_alter_contact_phone_alter_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subtask',
        ),
        migrations.AddField(
            model_name='task',
            name='subtask',
            field=models.ManyToManyField(blank=True, null=True, to='join_app.subtask'),
        ),
    ]
