# Generated by Django 6.0 on 2025-12-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0013_remove_task_subtask_task_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtask',
            field=models.ManyToManyField(blank=True, to='join_app.subtask'),
        ),
    ]
