# Generated by Django 6.0 on 2025-12-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0015_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='process',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('awaiting_feedback', 'Awaiting Feedback'), ('done', 'Done')], default='todo', max_length=20),
        ),
        migrations.DeleteModel(
            name='Board',
        ),
    ]
