# Generated by Django 6.0 on 2025-12-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_app', '0016_task_process_delete_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='upcoming_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
