# Generated by Django 6.0 on 2026-02-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_app', '0002_userprofile_email_userprofile_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
    ]
